version: "3.8"

services:
  client:
    container_name: frontend-assesment-client-dev
    image: frontend-assesment-client-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
  api:
    container_name: frontend-assesment-api-dev
    image: frontend-assesment-api-dev
    build:
      context: api
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "3080:3080"
